---
- name: Dependencies
  become: true
  package:
    name: "{{ tomcat_dependencies }}"
    state: present
  register: _install
  until: _install is succeeded
  retries: 3
  notify: Restart Tomcat

- name: Create Group
  become: true
  group:
    name: "{{ tomcat_group }}"
    gid: "{{ tomcat_group_gid | default(omit) }}"
    state: present
    system: true
  when: tomcat_group_manage | bool
  notify: Restart Tomcat

- name: Create User
  become: true
  user:
    name: "{{ tomcat_user }}"
    uid: "{{ tomcat_user_uid | default(omit) }}"
    group: "{{ tomcat_group }}"
    home: "{{ tomcat_user_home }}"
    shell: "/usr/sbin/nologin"
    state: present
    system: true
  when: tomcat_user_manage | bool
  notify: Restart Tomcat

- name: Necessary Dirs
  become:
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ tomcat_cache_dir }}"
    - "{{ tomcat_expand_dir }}"
  notify: Restart Tomcat

- name: Download Tomcat
  become: true
  maven_artifact:
    artifact_id: tomcat
    dest: "{{ tomcat_cache_dir }}/tomcat-{{ tomcat_version }}.tar.gz"
    extension: tar.gz
    group_id: org.apache.tomcat
    repository_url: "{{ tomcat_maven_repository_url | default(omit) }}"
    version: "{{ tomcat_version }}"
    validate_certs: "{{ tomcat_maven_validate_certs | bool }}"
  notify: Restart Tomcat

- name: Expand Tomcat
  become: true
  unarchive:
    dest: "{{ tomcat_expand_dir }}"
    src: "{{ tomcat_cache_dir }}/tomcat-{{ tomcat_version }}.tar.gz"
    remote_src: true
    creates: "{{ tomcat_expand_dir }}/apache-tomcat-{{ tomcat_version }}"
    owner: root
    group: "{{ tomcat_group }}"
    mode: "u=rwx,g=rx,o="
  notify: Restart Tomcat

- name: Uncomment Umask (Tomcat < 8.5)
  become: true
  lineinfile:
    path: "{{ tomcat_catalina_home ~ '/bin/catalina.sh' }}"
    group: "{{ tomcat_group }}"
    backrefs: true
    regexp: '^#(JAVA_OPTS="\$JAVA_OPTS -Dorg.apache.catalina.security.SecurityListener.UMASK=.*$)'
    line: "\\1"
    owner: root
    mode: "u=rwx,g=rx,o="
    state: present
  when: tomcat_version is version_compare("8.5.0","<")
